# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

def common_pods
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'KeychainAccess'
end

target 'Simple Login' do
  common_pods
  pod 'SideMenu', '~> 6.0'
  pod 'Toaster'
end
