# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!

def common_pods
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'KeychainAccess'
end

target 'Simple Login' do
  common_pods
  pod 'SideMenu', '~> 6.4.8'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Toaster'
  pod 'MarqueeLabel'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Gifu'
  pod 'Differ'
  pod 'SwiftyStoreKit'
end

target 'Share Extension' do
  common_pods
end
